MovieShopMVC/Controllers/CastsController.cs
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class CastsController : Controller
    {
        private readonly ICastService _castService;

        public CastsController(ICastService castService)
        {
            _castService = castService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var cast = await _castService.GetCastDetails(id);
            return View(cast);
        }
    }
}

MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;//Depency injection

        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        //GET
        public async Task<IActionResult> Details(int id)
        {
            var movie = await _movieService.GetMovieDetails(id);

            return View(movie);
        }
        public IActionResult Genre()
        {
            throw new System.NotImplementedException();
        }
    }
}

MovieShopMVC/Views/Movies/Details.cshtml
@model ApplicationCore.Models.MovieDetailsResponseModel
@{
    ViewData["Title"] = "Detail Page";
}
<!--changedetails-->

<div>
    <div class="row">
        <div class="col-md-12 column" style="background-image:url(@Model.BackdropUrl); background-size: cover;">
            <div class="col-4">
                <div class="row">
                    <div class="col-md-3 offset-2">
                        <div>
                            <img src="@Model.PosterUrl" class="img" alt="@Model.Title" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="col offset-1">
                <div class="row mt-2">
                    <div class="col-12">
                        <h1 class="text-white">
                            @Model.Title
                        </h1>
                        <small class="text-white"> @Model.Tagline </small>
                        <div class="row">
                            <div class="col-5 text-secondary font-weight-bold mt-1 ">
                                <p>@Model.RunTime m | @Model.ReleaseDate.Value.Date.Year</p>
                            </div>
                            <div class="col-8">
                                @foreach (var genre in Model.Genres)
                                {
                                    <a class="badge badge-pill badge-dark ml-1" asp-route-id="@genre.Id">
                                        @genre.Name
                                    </a>}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            

            <div class="row">
                <div class="col-4 mt-3">
                    <h4>
                        <span class="badge badge-warning">
                            @Model.Rating?.ToString("0.00")
                        </span>
                    </h4>
                </div>
            </div>

            <div class="row">
                <div class="col-12 text-light mt-2">
                    @Model.Overview
                </div>
            </div>


            <div class="col-md-2 mt-4 offset-1">
                <ul class="list-group">
                    <li class="list-group-item">

                    </li>
                    <li class="list-group-item">
                        <button type="button"
                                class="btn btn-light btn-block btn-sm">
                            <i class="far fa-edit mr-1"></i>
                            REVIEW
                        </button>
                    </li>
                    <li class="list-group-item">
                        <button type="button"
                                class="btn btn-light btn-block btn-sm">
                            <i class="fas fa-play mr-1"></i> TRAILER
                        </button>
                    </li>

                    <li class="list-group-item">
                        <a class="btn btn-light btn-lg btn-block btn-sm">
                            BUY @Model.Price
                        </a>

                        <a class="btn btn-light btn-lg btn-block btn-sm">
                            WATCH MOVIE
                        </a>
                    </li>
                </ul>
            </div>

        </div>
    </div>
</div>
    
    
<div class="row mt-3">
    <div class="col-4 bg-light">
        <h5>MOVIE FACTS</h5>
        <hr>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                Release Date
                <span class="badge badge-pill badge-dark">@Model.ReleaseDate.Value.ToShortDateString()</span>
            </li>
            <li class="list-group-item">
                Run Time
                <span class="badge badge-pill badge-dark">@Model.RunTime.Value m</span>
            </li>
            <li class="list-group-item">
                Box Office
                <span class="badge badge-pill badge-pill badge-dark">
                    @Model.Revenue?.ToString("C0")
                </span>
            </li>
            <li class="list-group-item">
                Budget
                <span class="badge badge-pill badge-dark">
                    @Model.Budget?.ToString("C0")
                </span>
            </li>
        </ul>
    </div>


    <div class="col-8">
        <h5>CAST</h5>
        <ul class="list-group list-group-flush">

            @foreach (var cast in Model.Casts)
            {
                <a class="text-dark" asp-controller="Casts" asp-action="Details" asp-route-id="@cast.Id">
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-2">
                            <img src="@cast.ProfilePath"
                                 class="rounded-circle"
                                 style="width:30px; height: 45px;"
                                 alt="@cast.Name" />
                        </div>
                        <div class="col-3">
                            @cast.Name
                        </div>
                        <div class="col-4">
                            @cast.Character
                        </div>
                    </div>
                </li>
                </a>
            }

        </ul>

    </div>
</div>